### ISSUE TITLE
Support for multilingual information

### ISSUE THREAD

**Issue by pvretano** [opengeospatial/WFS_FES#134]
What is the thinking about supporting multilingual information (i.e. titles, descriptions, etc.)?
In Canada there is a requirement to support both French and English in government provided services.  As far as my thinking goes, I can see two possibilities:
(a) Different languages are supported at different service endpoints.
(b) We update the title, description, etc. structures to be arrays that include a "lang" property for the specific language.
Whatever the thinking is, we should include some informative text in the specification about supporting multiple language.

**Comment by cportele** [comment]
(c) Since we require support for HTTP 1.1, content negotiation includes the selection of the language used in the content. This is how multilingual support is in general supported on the Web, I think. 

This is already implied in the current requirements, but it is true, we should add informative text to make this clear.

Making all text properties multilingual (b) would be another option, but I think most clients will want the text in a single language and this is how the web is designed. Just like we do not return GeoJSON and GML in a single response. And arrays are more complex to process.

(a) would ignore the language-selection capabilities of HTTP, which are well-supported, for example, by web browsers.

**Comment by akuckartz** [comment]
How JSON-LD deals with that: https://www.w3.org/TR/json-ld/#string-internationalization
