### ISSUE TITLE
Usage of format query parameters

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/WFS_FES#141]
The specification suggests in several examples and notes that a format query parameter in request can be used to overwrite the ```Accept``` header (e.g. in chapter [7.8. Encodings](https://cdn.rawgit.com/opengeospatial/WFS_FES/3.0.0-draft.1/docs/17-069.html#_encodings_2)).

Doesn't this proposal contradict REST principles?

**Comment by cportele** [comment]
+1 to @jvanulde. 

As the text states, a capability is needed to have encoding-specific URIs for resources in order to express links, for example, to alternate representations of the same resource. I.e. this is required to support a hypermedia approach and express the relevant links in the response. This is also quite common, at least where a server supports multiple representations. 

There are multiple ways how to implement this and we do not mandate any particular approach how this is implemented.
