### ISSUE TITLE
/req/gmlsf0/definition (Requirement 37), /req/gmlsf0/content (Requirement 38) and Note at 8.4: Simple Features

### ISSUE THREAD

**Issue by PeterParslow** [opengeospatial/WFS_FES#150]
1. /req/gmlsf0/definition & the note highlight the difficulty: properly, the HTTP media type applies to the whole response, and yet the feature collection does not conform to GML simple feature.

The note points this out (that the wfs:FeatureCollection itself is not a GML simple feature)

requirement /req/gmlsf0/content is clear that it applies to the features in the collection. So the note only applies to /req/gmlsf0/definition (requirement 37).

2. ALSO /req/gmlsf0/content contains the only occurence of the phrase "feature resource". If this is (was) intended, then what is it supposed to mean?

3. And finally, see http://ogc.standardstracker.org/show_request.cgi?id=554 (which I've only just got round to posting): the wfs:FeatureCollection doesn't formally meet the rules for a GML feature collection. WFS 3.0 gets round this by adding the middle of the three SHALLs in Requirement 38 (/req/gmlsf0/content). I think it would be better to fix the XSD - even though it would then differ from the WFS 2 XSD, by being stricter.

**Comment by cportele** [comment]
13-MAY-2019 Conference call: Peter will have a look when editing the XML schemas.

**Comment by pvretano** [comment]
Fixing the schemas would require the following:

(1) Remove the current definition of feature collection which was meant to be a generic container of XML-encoded features (including GML-encdoded features) and also include additional metadata like timeStamp and numberMatched.
(2) Replace it with a strict GMLSF feature collection definition which does not include any of this stuff

This fix would have two effects.  First, I suppose this would solve issue #234 since without numberReturned and numberMatched there is no longer a streaming issue.  Second, it would introduce a dependency to GML which we, as we did in WFS 2.X, tried to avoid.

Another option might be to define 2 response containers.  One for strict GMLSF compliance and a second, more loose, container for any XML-encoded features including GML-encoded features.

**Comment by cportele** [comment]
Decision: Change to GMLSF-conformant Feature Collection. The additional properties like numberMatched would have to go to a HTTP header, same for the links. Peter will update the XSD and the GMLSF conformance class. Clemens will review the changes and update the ATS.
