### ISSUE TITLE
Protect clients against large datasets/high limit values

### ISSUE THREAD

**Issue by aaime** [opengeospatial/WFS_FES#165]
During today's compliance meeting we discussed an issue with CITE tests asking for the items endpoint without any extra parameter, which depending on the server implementation, could cause the client to load very large datasets.
A server will protect itself somehow (by setting a low page size, or by never loading the full dataset in memory), can the client do the same, or should the spec be amended? I was asked to open a ticket on behalf of the group :-)

The current metadata is not telling the client how many features are there in a collection, the client has to ask for the first page and get the total count from that response.
It could very well be that the client just has to check the API document, see if the default limit value is suitable, and if not, make a request with an explicit and small enough limit value, but during today's discussion there were concerns about the naive client auto-generated from the API document, which would likely not have such smarts.

**Comment by cportele** [comment]
I see the point, but again, it is not easy for all implementations to determine the number of features, which is why we have removed the resulttype=hits capability from the Core. See #22. 

I guess a server that is configured so that it overloads many clients by default will not be used a lot, so it is in the interest of the provider to use reasonable limits for the planned use. Maybe this isn't such an issue in practice?

**Comment by cportele** [comment]
20-MAY-2019 Conference call: This should not result in a change to the normative statements, but Chuck will check, if this should be considered in the Abstract Test Suite.

**Comment by cmheazel** [comment]
I believe the updated ATS covers this.  This issue can be closed.
