### ISSUE TITLE
default representation

### ISSUE THREAD

**Issue by tomkralidis** [opengeospatial/WFS_FES#179]
Is there such thing as a a default representation? Should there be? Context: I am working on the [OWSLib](https://github.com/geopython/OWSLib) WFS 3 client and encounter the following differences:

* https://geo.weather.gc.ca/geomet/features (pygeoapi) returns JSON as default
* https://www.ldproxy.nrw.de/rest/services/kataster/ returns HTML as default and needs `f=json` for JSON output

From a client perspective we are locking on JSON, so if a WFS 3 base URL needs a query parameter to enable JSON then we handle that differently as opposed to one which returns JSON as default.

**Comment by cportele** [comment]
In ldproxy we changed the default from HTML to JSON (so the nrw.de would soon also return JSON as the default). The reason is that browsers will send an accept header with a HTML preference and probably other request will prefer JSON (or XML or …). 

I guess we should at least have a discussion about this somewhere. We cannot have strict rules as there is no mandatory encoding, but we might recommend to return JSON by default, if it is supported. Just like we recommend support for GeoJSON, if it works for the dataset.

**Comment by jvanulde** [comment]
My view is that a default encoding is unnecessary.

**Comment by pvretano** [comment]
@jvanulde ++++1!

@tomkralidis  The client and server should handshake to determine a suitable representation.  Several options available ... set the Accept header with representations your client can handle (with appropriate q values); use the OPTIONS method (it if is available -- should be) to find what representations are available for a resource.

**Comment by cportele** [comment]
@pvretano - Is there a standard way to specify the supported media types in the response of an OPTIONS request? You have "Allow" for the methods, but nothing for the media types AFAIK. Yes, you could include this information in a custom header or the payload, but there is nothing that is generally supported by clients. Or am I missing something?

**Comment by pvretano** [comment]
@cportele from the HTTP RFC, section 9.2: "A 200 response SHOULD include any header fields that indicate optional features implemented by the server and applicable to that resource (e.g., Allow), possibly including extensions not defined by this specification."
If I am understanding the HTTP RFC, OPTIONS can tell a client what methods and representations are available for a resource.  So, a client can call OPTIONS to figure out which representations can be listed in the Accept header.

**Comment by cportele** [comment]
@pvretano - so you say that the server should include an "Accept" header in the response with the allowed values? I have never seen that and "Accept" is a request header anyhow. Do you have an example where that is used? Or a link where an "extension not defined by this [the http] specification" is specified?

**Comment by pvretano** [comment]
@cportele As far as I know, the most common response is the Allow header but there is nothing in the specification that prevents other information from being returned.   I guess I would say that using OPTIONS as I have suggested does not violate the HTTP RFC.  I'll poke around for some usage examples...

**Comment by cportele** [comment]
HTTP restricts "Allow" to "list the set of methods supported by the resource identified by the Request-URI." This is explicitly restricted to the HTTP methods and does not include any other information. That is, this information does not belong into "Allow" response header and even if we would use it for this purpose no HTTP client would expect that, so that doesn't help in my view.

**Comment by pvretano** [comment]
@cportele I am not suggesting that we use Allow to indicate available representations.  Allow is not the only header that OPTIONS may return.  What I am saying is that the response to the OPTIONS method is "typically" the Allow header that indicates what methods may be used with the resource.  However, the HTTP RFC does not restrict other headers or information from being returned in response to an OPTIONS request.  Accept, for example, could be returned to indicate the available representations for a resource.  I don't know if this is common usage  but it is certainly not restricted.  As I said, I'll have to poke around to see get a better sense of the use of OPTIONS.

**Comment by pvgenuchten** [comment]
I'm fine to leave it open to the implementators, since it won't break the obvious usecases. However if we want to define an encoding, these thoughts: a default encoding is relevant for softwares that are not well informed of web standards. So we should guess on which domain we expect most unaware developers, requiring which encoding? Some typical use cases: 
- a visitor opening a feature in a browser (browser will send html header)
- a search engine crawling the service (crawler will send html header)
- leaflet/openlayers requesting a set of features (it will send the json header)
- a desktop gis following a link from a feature to another feature (does it expect a webpage or a feature?)
- ...

**Comment by hannesaddec** [comment]
From the good old NIX days pipe command days- a default value is always set, even if other options are available/negotiable (which is what Peter is aiming).

**Comment by cportele** [comment]
15-April-2019 Teleconference: No pre-defined default representation, we will just follow the HTTP rules but do not force servers into a default encoding.

**Comment by hannesaddec** [comment]
So HTML and PLAIN will always be supported ?
https://www.w3.org/Protocols/HTTP/Response.html -> The Content-Type used for the data may be any Content-Type which the client has expressed its ability to accept, or text/plain, or text/html. That is, one can always assume that the client can handle text/plain and text/html.

**Comment by cportele** [comment]
That must be an arcane resource, probably mostly relevant for historians! In any case, it does not say that every server must be able to return text/plain or text/html. It says that all clients are expected to be able to handle these types (which clearly is not the case for any WxS client, by the way).

The HTTP 1.1 spec is clearer: "If no Accept header field is present, then it is assumed that the client accepts all media types". That is, it is up to the server to decide what content type to return.

**Comment by pvgenuchten** [comment]
an update here, in my comment above i incorrectly suggested that search engine crawler would send a html accept header.... this is (no longer) the case for google as well as yandex. As far as I know, these engines and their structured data parser does not send an accept header. With json as a default, the crawler will try to parse the json content, which may not give the expected result. So for optimal indexing in search engine make sure that html is the default output (if no accept header is sent)
