### ISSUE TITLE
Is OpenAPI mandatory or not. Req 2 B seems explicit

### ISSUE THREAD

**Issue by joanma747** [opengeospatial/WFS_FES#247]
Section .5.2. starts:
> This document uses OpenAPI 3.0 fragments as examples and to formally state requirements. However, using OpenAPI 3.0 is not required for implementing a server.  
> Therefore, the Core requirements class only requires that an API definition is provided and linked from the landing page.

But Requirement 2 | /req/core/root-success B says:

> The content of that response SHALL be based upon the OpenAPI 3.0 schema landingPage.yaml and include at least links to the following resources:

Seems very specific to me. Is it or is it not mandatory?.

My personal opinion (does not seem to be the consensus) is that we should be brave and go for a clear support to OpenAPI. It is one of the main new things and we cannot hide it. Don't doing that will force us into constant contradictions like this ones in req 2. In practice is all about swagger.

**Comment by cportele** [comment]
It is as it says in the quoted text:

* OpenAPI 3.0 is used to express schemas in normative statements (independent of the API definition or the encoding). This is different from requiring implementations to support OpenAPI 3.0.
* There is no requirement to provide an API definition in OpenAPI 3.0. Yes, since currently the only API definition conformance class there is an expectation that current implementations will in general provide an API definition in OpenAPI 3.0, but once we have OpenAPI 3.1 etc. this may change with time and we don't want to be locked into OGC API implementations having to provide OpeAPI 3.0 forever. This is explained in 5.5.2 from which you quoted the first sentence.

**Comment by joanma747** [comment]
I'm sorry. You have to be very smart reading normative texts. I see now that you are talking about "kind-of-JSON- Schema" in the OpenAPI flavor. I have read it is a bit different from a "Authentic" JSON Schema (that BTW has not been approved yet). 
IMHO it could be easy to talk about JSON Schema but I understand that you prefer the other expression.

Thanks for your clarification. We can close the issue. Actually there was no issue in the first place.
